version: "3.7"

# For deployment on our server with traefik at chat.palcollective.com
name: chat-mattermost
services:
  app:
    image: mattermost/mattermost-preview
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ant.rule=Host(`chat.palcollective.com`)"
      - "traefik.http.routers.ant.entrypoints=websecure"
      - "traefik.http.routers.ant.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik"
    networks:
      - traefik

networks:
  traefik:
    external: true